FROM node:18-alpine

WORKDIR /app

COPY frontend/package.json /app/package.json
RUN npm install

COPY frontend/ /app/

EXPOSE 5173

ENV VITE_API_BASE="http://localhost:8000"

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173", "--strictPort"]
